export const CREATE_REPO = 'CREATE_REPO';
export const UPDATE_REPO = 'UPDATE_REPO';
export const DELETE_REPO = 'DELETE_REPO';
export const FETCH_ALL_REPOS = 'FETCH_ALL_REPOS';

export const FETCH_ALL_GIT_REPOS = 'FETCH_ALL_GIT_REPOS';
export const FETCH_GIT_REPO = 'FETCH_GIT_REPO';
export const CLEAR_GIT_REPO = 'CLEAR_GIT_REPO';
export const REPO_NOT_FOUND = 'REPO_NOT_FOUND';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const FETCH_ALL_ACTIVITIES = 'FETCH_ALL_ACTIVITIES';
export const TRACK_ACTIVITY = 'TRACK_ACTIVITY';
